import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/app/components/Navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="flex-col"> 
              <Navbar />
            <div>{children}</div>
          </div>
      </body>
    </html>
  )
}
